# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/CC6_UMIP_ACCESS.a
LOCAL_BUILT_MODULE_STEM:=CC6_UMIP_ACCESS.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=CC6_UMIP_ACCESS
LOCAL_MODULE_STEM:=CC6_UMIP_ACCESS.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libsepdrm.so
LOCAL_BUILT_MODULE_STEM:=libsepdrm.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsepdrm
LOCAL_MODULE_STEM:=libsepdrm.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libc libcrypto libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/libsepdrm.a
LOCAL_BUILT_MODULE_STEM:=libsepdrm.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsepdrm
LOCAL_MODULE_STEM:=libsepdrm.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libsecurity_api.so
LOCAL_BUILT_MODULE_STEM:=libsecurity_api.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsecurity_api
LOCAL_MODULE_STEM:=libsecurity_api.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libc libcrypto liblog libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libdiskkeyencrypt.so
LOCAL_BUILT_MODULE_STEM:=libdiskkeyencrypt.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libdiskkeyencrypt
LOCAL_MODULE_STEM:=libdiskkeyencrypt.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libc libcrypto libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/libsecurity_api.a
LOCAL_BUILT_MODULE_STEM:=libsecurity_api.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsecurity_api
LOCAL_MODULE_STEM:=libsecurity_api.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/libsecurity_sectoken.a
LOCAL_BUILT_MODULE_STEM:=libsecurity_sectoken.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsecurity_sectoken
LOCAL_MODULE_STEM:=libsecurity_sectoken.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libsecurity_sectoken.so
LOCAL_BUILT_MODULE_STEM:=libsecurity_sectoken.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libsecurity_sectoken
LOCAL_MODULE_STEM:=libsecurity_sectoken.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libc libcrypto libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=eng
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/libmiscutils.a
LOCAL_BUILT_MODULE_STEM:=libmiscutils.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libmiscutils
LOCAL_MODULE_STEM:=libmiscutils.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/ExtApp_qa_op_code.h include/umip_access.h include/acd_reference.h include/fkpmidware.h include/mvsepfwapi.h include/prdevcert.h include/secure_token.h include/security_api.h include/sepdrm-common.h include/sepdrm.h include/sepdrm-log.h include/sepmvdrm.h include/umip_access.h include/chaabi_error_codes.h include/secure_token.h
LOCAL_COPY_HEADERS_TO:=chaabi
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/sepdrm.h include/sepdrm-common.h
LOCAL_COPY_HEADERS_TO:=libsepdrm
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/security_api.h
LOCAL_COPY_HEADERS_TO:=libsecurity_api
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/disk_key_encrypt.h
LOCAL_COPY_HEADERS_TO:=libdiskkeyencrypt
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/ExtApp_qa_op_code.h include/umip_access.h include/acd_reference.h include/fkpmidware.h include/mvsepfwapi.h include/prdevcert.h include/secure_token.h include/security_api.h include/sepdrm-common.h include/sepdrm.h include/sepdrm-log.h include/sepmvdrm.h include/umip_access.h include/chaabi_error_codes.h include/secure_token.h
LOCAL_COPY_HEADERS_TO:=chaabi
include $(BUILD_COPY_HEADERS)
endif
