# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libstagefrighthw.so
LOCAL_BUILT_MODULE_STEM:=libstagefrighthw.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libstagefrighthw
LOCAL_MODULE_STEM:=libstagefrighthw.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libbinder libutils libcutils libui libdl libstagefright_foundation libc libstdc++ libm
include $(BUILD_PREBUILT)
endif
