# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libva_videoencoder.so
LOCAL_BUILT_MODULE_STEM:=libva_videoencoder.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libva_videoencoder
LOCAL_MODULE_STEM:=libva_videoencoder.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libutils libva libva-android libva-tpi libui libutils libhardware libintelmetadatabuffer libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libintelmetadatabuffer.so
LOCAL_BUILT_MODULE_STEM:=libintelmetadatabuffer.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libintelmetadatabuffer
LOCAL_MODULE_STEM:=libintelmetadatabuffer.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/VideoEncoderHost.h include/VideoEncoderInterface.h include/VideoEncoderDef.h include/IntelMetadataBuffer.h
LOCAL_COPY_HEADERS_TO:=libmix_videoencoder
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/VideoEncoderHost.h include/VideoEncoderInterface.h include/VideoEncoderDef.h include/IntelMetadataBuffer.h
LOCAL_COPY_HEADERS_TO:=libmix_videoencoder
include $(BUILD_COPY_HEADERS)
endif
