# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=EXECUTABLES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/securityfileservice
LOCAL_BUILT_MODULE_STEM:=securityfileservice
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=securityfileservice
LOCAL_MODULE_STEM:=securityfileservice
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/bin
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libbinder libutils libjavacore libstlport liblog libcutils libstlport libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/AsfVersionAosp.h
LOCAL_COPY_HEADERS_TO:=asfaosp
include $(BUILD_COPY_HEADERS)
endif
