# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libjpegdec.so
LOCAL_BUILT_MODULE_STEM:=libjpegdec.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libjpegdec
LOCAL_MODULE_STEM:=libjpegdec.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libutils libva-android libva libva-tpi libhardware libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libjpeg_hw.so
LOCAL_BUILT_MODULE_STEM:=libjpeg_hw.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libjpeg_hw
LOCAL_MODULE_STEM:=libjpeg_hw.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libutils liblog libjpegdec libhardware libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=EXECUTABLES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/testjpegdec
LOCAL_BUILT_MODULE_STEM:=testjpegdec
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=testjpegdec
LOCAL_MODULE_STEM:=testjpegdec
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/bin
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libutils libva-android libva libva-tpi libjpegdec libhardware libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/JPEGDecoder.h include/JPEGCommon.h include/ImageDecoderTrace.h
LOCAL_COPY_HEADERS_TO:=libjpegdec
include $(BUILD_COPY_HEADERS)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/JPEGDecoder_libjpeg_wrapper.h
LOCAL_COPY_HEADERS_TO:=libjpeg_hw
include $(BUILD_COPY_HEADERS)
endif
