# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libva_videodecoder.so
LOCAL_BUILT_MODULE_STEM:=libva_videodecoder.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libva_videodecoder
LOCAL_MODULE_STEM:=libva_videodecoder.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libmixvbp libva libva-android libva-tpi libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/VideoDecoderHost.h include/VideoDecoderInterface.h include/VideoDecoderDefs.h
LOCAL_COPY_HEADERS_TO:=libmix_videodecoder
include $(BUILD_COPY_HEADERS)
endif
