# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libmix_videovpp.so
LOCAL_BUILT_MODULE_STEM:=libmix_videovpp.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libmix_videovpp
LOCAL_MODULE_STEM:=libmix_videovpp.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libutils libui liblog libhardware libdrm libdrm_intel libwsbm libva libva-android libva-tpi libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=EXECUTABLES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/csc_vpp
LOCAL_BUILT_MODULE_STEM:=csc_vpp
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=csc_vpp
LOCAL_MODULE_STEM:=csc_vpp
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/bin
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libhardware libmix_videovpp libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/VideoVPPBase.h
LOCAL_COPY_HEADERS_TO:=libmix_videovpp
include $(BUILD_COPY_HEADERS)
endif
